### PR TITLE
ChangelogTasks Unit Tests and Fixes

### LINKED ISSUE #1099: Release sections containing list items that span multiple lines cause truncation in GetReleaseSections() method
### Usage Information

6.3.0 / 7.0.101 / net6.0 / Windows

### Description

When parsing a changelog file with `GetReleaseSections()` that has a release section that contains list items that span multiple lines, the remaining content of that section is truncated.

Example of a changelog file containing a release section that has a list item that spans multiple lines:
```markdown
# Changelog
## [Unreleased]
### Added
- Some text that spans
  multiple lines
- This text is also lost
```

### Reproduction Steps

1. Parse the following changelog file content with `GetReleaseSections()`
```markdown
# Changelog
## [Unreleased]
### Added
- Some text that spans
  multiple lines
- This text is also lost
```
2. Inspect `Notes` array content on the returned `ReleaseSection`

### Expected Behavior

`Notes` array contains the following elements:

```
[0]: "### Added"
[1]: "- Some text that spans"
[2]: "  multiple lines"
[3]: "- This text is also lost"
```

### Actual Behavior

`Notes` array contains the following elements:

```
[0]: "### Added"
[1]: "- Some text that spans"
```

### Regression?

_No response_

### Known Workarounds

Do not use multiple lines for list items when writing a changelog file.

### Could you help with a pull-request?

Yes

### PR DESCRIPTION
**Pull request by sandrofigo**
- Adds unit tests for `ChangelogTasks`
- Fixes `ReleaseSection` end index when changelog contains empty lines
- Fixes `ExtractChangelogSectionNotes` not throwing the intended exception
- Fixes `IsEmpty` property on `ReleaseNotes` when `Notes` are empty strings

Closes #1099 

I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

### CODE REVIEW

**Comment by matkoch** [comment]
Could you add some test cases for the format that this project uses? I.e., without sub-headings for `Added` etc.

**Comment by sandrofigo** [comment]
@matkoch I have added two variants for the NUKE changelog flavor.

**Comment by sandrofigo** [comment]
Ready to merge again after rebasing onto develop.

@matkoch Is it intended that I keep the feature branch up-to-date manually with the develop branch by rebasing and force pushing once in a while?

**Comment by matkoch** [comment]
Hi @sandrofigo
no you don't need to do anything. I do rebases myself (also noted in the contribution guidelines). I'll merge this for next release for sure.

**Comment by sandrofigo** [comment]
@matkoch It's a bummer that this PR didn't make it into the new release. Let me know if there is something I need to change or when you plan to include this.

**Comment by matkoch** [comment]
Sorry but I really needed to get all the pending work released. Yes, I also merged some recent PRs, but this one takes a bit more time to review. In any case, I expect there will be reports about this release, so I'm sure another release will follow shortly!

**Comment by matkoch** [comment]
@sandrofigo, [this change](https://github.com/nuke-build/nuke/pull/1130/files#diff-97b9fc8cdf6c9b5de572839c895b42ac9e873c518b9ae5b560e55da7fd49c474L207-R207) has [broken version updates](https://github.com/nuke-build/nuke/commit/527075ca533611aab21a67b148fe62ab52db20b2).

I reverted some changes and also deleted some tests. If you want, feel free to bring them back. For my purpose, the task is working as intended again.

**Comment by sandrofigo** [comment]
@matkoch I will try to come up with a fix for `FinalizeChangelog()` and `UpdateVersionSummary()` and would also readd the unit tests/fixes.

**Comment by sandrofigo** [comment]
@matkoch Have a look at this PR https://github.com/nuke-build/nuke/pull/1250 and let me know what you think.

**Pull request merged**
