### PR TITLE
Adding Fixie.json file to support Fixie.

### PR DESCRIPTION
**Pull request by phillipsj**
Creating the Fixie json file that will add support for the Fixie testing
frameworks. Completing #706.

I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

### CODE REVIEW

**Comment by matkoch** [comment]
top-level help text still missing 🤔

**Comment by phillipsj** [comment]
Hmm, I will get that added.  Strange, as I remember doing it, but I was
distracted.

**Comment by phillipsj** [comment]
I have fixed the missing global help.

**Comment by matkoch** [comment]
Thanks for your contribution! 😄🎉

**Pull request merged**
