### PR TITLE
Treat an empty CI-specific environment variable as non-existing

### PR DESCRIPTION
**Pull request by dennisdoomen**
When running Nuke from inside a LINUX docker container, we tend to pass the TEAMCITY_VERSION from the host to the container. However, that will set the value to an empty string, even though the variable did not exist on the host. This is fixed for Team City and all the other CI providers.

There were no tests that I could update/amend

I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

### CODE REVIEW

**Comment by dennisdoomen** [comment]
@matkoch any idea what's going on with the builds?

**Comment by matkoch** [comment]
Nothing related to your changes

**Comment by dennisdoomen** [comment]
In that case it would be nice to get a pre-release with these changes.

**Comment by matkoch** [comment]
@dennisdoomen are the environment variables propagated by default, or are you doing this for some other reason? I'm asking because in case of the first, we should make the same changes to all CI server interfaces. In the latter case, the better option would be to pass `--host console`.

**Comment by dennisdoomen** [comment]
We do something like this:

```
docker run --rm --name $env:build_container_name `
 -v /var/run/docker.sock:/var/run/docker.sock `
 -v $PWD/$env:artifacts_dir`:/repo/$env:artifacts_dir `
 -v $PWD/.git:/.git `
 --network host `
 -e TEAMCITY_VERSION=$env:TEAMCITY_VERSION  `
```

So even if the `TEAMCITY_VERSION` env variable wasn't set, the docker container will see it as `""`. 

So yes, most likely it will also affect the other build systems in a similar way.

**Comment by matkoch** [comment]
But why are you passing the TeamCity version like this?

**Comment by dennisdoomen** [comment]
How else does Nuke know that the build is running on TeamCity

**Comment by dennisdoomen** [comment]
So? Are you accepting my PR?

**Comment by matkoch** [comment]
We can do it like that. But could you apply the same logic to all other CI
interfaces?

**Comment by dennisdoomen** [comment]
Sure, will do.

**Comment by cmenzi** [comment]
When an empty envvar is treated as not existent, how to deal with switch only parameters?

For example if you have a - - force parameter and a env var FORCE should do the same?

Or do this only apply on CI related env vars?

**Comment by matkoch** [comment]
`envvar=1` … besides, we’re only talking about CI system detection here.
Not general parameter resolution.

**Pull request merged**
