### PR TITLE
Add VS2022 paths to MSBuildToolPathResolver

### PR DESCRIPTION
**Pull request by mvestergaard**
I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

### CODE REVIEW

**Comment by mvestergaard** [comment]
It looks like this was changed from my original commit, to something that won't work. The `folder` isn't passed into `GetFromVs2017Instance`

**Comment by matkoch** [comment]
yep my bad

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/MSBuild/MSBuildToolPathResolver.cs#L47
https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/MSBuild/MSBuildToolPathResolver.cs#L70

**Comment by matkoch** [comment]
Thanks! Also for catching up so quickly.

**Pull request merged**
