### PR TITLE
Fix finding VS BuildTools 2022

### PR DESCRIPTION
**Pull request by ghost**
Fixes the search path for VS22 BuildTools, which seems to still install to Program Files (x86). 

The path on a docker container we have that uses vs_buildtools.exe to install VS BuildTools 2022:
image

Install Script:
```# MSbuildtools
RUN cd sources && \
    curl -SL --output vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe && \
    \
    (start /w vs_BuildTools.exe --quiet --wait --norestart --nocache \
    --add Microsoft.VisualStudio.Workload.MSBuildTools \
    --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools \
    --includeRecommended --includeOptional \
    || IF "%ERRORLEVEL%"=="3010" EXIT 0) && \
    \
    del /q vs_buildtools.exe
```

I confirm that the pull-request:

- [X] Follows the contribution guidelines
- [X] Is based on my own work
- [X] Is in compliance with my employer

### CODE REVIEW

**Comment by joergpichler** [comment]
This is also currently a blocker for us. Need this merged asap :)

**Comment by dpisanu** [comment]
I approve of this fix. 👍

**Comment by ghost** [comment]
Hey, @matkoch any way we could get this merged? I temporarily worked around this by installing full vs community to our build agents instead, but it does slow down our image builds quite a bit vs just installing the buildtools.

**Comment by matkoch** [comment]
Hi, unfortunately, it's going to be a while. I'm currently occupied with other things.

**Comment by MichaelKetting** [comment]
We also ran into this. There is the option of injecting the correct path so it's not a blocker, but still, is there something you need to help with releasing bugfixes in case an issue isn't as easily fixable?

**Pull request merged**
