### PR TITLE
Add DotNetBuild as a copy of MSBuild

### PR DESCRIPTION
**Pull request by andrewlock**
I don't really understand how the codegen works here, so was just trying something out... The source generation only seems to work occasionally, so not sure if I'm doing something wrong. I tried running `./build.ps1 GenerateTools` but that seems to update lots of files, and always errors with `Couldn't load metadata file 'ILRepack.json'`

As already discussed, not sure if this is what you want, or if there's a better way of duplicating MSBuild for `dotnet msbuild`, but this is going to be a blocker for me, so wanted to try something out! 🙂

I confirm that the pull-request:

- [ ] Follows the contribution guidelines
- [ ] Is based on my own work
- [ ] Is in compliance with my employer

### CODE REVIEW

**Comment by matkoch** [comment]
@andrewlock will take a look as soon as I can. In the meantime, you should be able to [generate the tasks manually](https://github.com/nuke-build/playground/blob/master/build/tool-generation/tool-generation.csproj#L17) if it's urgent. Probably need to copy the [manually implemented part](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/DotNet/DotNetTasks.cs) alongside.

`ILRepack.json` indeed has a syntax error. Thanks for noticing!

**Comment by andrewlock** [comment]
No problem @matkoch, I was mostly just trying out things to see how the project works 🙂 

I wasn't sure if this was the best approach (copy-pasting from the MSBuild.json) or potentially something like [this PR](https://github.com/nuke-build/nuke/pull/713), which tries to "resuse" the MSBuildSettings to avoid duplication? I just tried out the latter in a local project and it seems to work pretty well, so it may be a better option?

**Comment by matkoch** [comment]
It's a bit different from both of your drafts.

Commit: https://github.com/nuke-build/nuke/commit/0f2c0710008ac1c5bfc47f3e9bff63febb246376
File: https://github.com/nuke-build/nuke/blob/develop/build/specifications/DotNet.json

If you can, please check if that file works locally for you. (Or just browse the specification file.)

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>🏗 The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>

**Comment by andrewlock** [comment]
Thanks for taking a look @matkoch! 

I think this line should have `msbuild` as the definite argument though right?

https://github.com/nuke-build/nuke/blob/0f2c071000/build/specifications/DotNet.json#L409

Also, don't know if you want to add the reference to the top: https://raw.githubusercontent.com/dotnet/docs/main/docs/core/tools/dotnet-build.md

Thanks again!

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>🏗 The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>
<blockquote></blockquote>

**Comment by matkoch** [comment]
Both true and fixed :)

**Pull request closed without merging**
