### PR TITLE
Add ability to use TeamCity logger on DotNetTestSettings

### PR DESCRIPTION
**Pull request by batzen**

### CODE REVIEW

**Comment by matkoch** [comment]
can you please change the existing one for `DotNetBuildSettings` instead? I guess that was a mistake..

**Comment by batzen** [comment]
Wasn't a mistake. This PR enables live test reporting in TeamCity when using DotNetTest.

**Comment by batzen** [comment]
Don't know why your changes show up here...

**Comment by matkoch** [comment]
I'm saying mine was a mistake... There already is a method for `DotNetBuildSettings` ... and it makes no sense there...

Don't worry about my changes, I'll rebase myself then.

**Comment by batzen** [comment]
Now i am confused even more.
Both `AddTeamCityLogger` methods make sense. One for proper live test result publishing and one for proper structure compile/build logging.

**Comment by matkoch** [comment]
Ahh true. I forgot it was about build messages having better colorization. I'll merge.. but in any case, you can also add a nuget package to the test project, which has the same effect but induces less "teamcity awareness" in the build project.

**Comment by matkoch** [comment]
Thanks for your contribution! 😄🎉

**Pull request merged**
