### PR TITLE
Allow to derive from OutputSink

### LINKED ISSUE #699: Allow to create custom OutputSinks
Currently, the public class `OutputSink` has `internal` abstract methods which are impossible to override except in Nuke assembly.

```
        internal abstract void WriteNormal(string text);
        internal abstract void WriteSuccess(string text);
        internal abstract void WriteTrace(string text);
        internal abstract void WriteInformation(string text);
```

In order to allow to create custom OutputSinks, those methods should be `protected internal`.

### PR DESCRIPTION
**Pull request by cmenzi**
Currently, the public class `OutputSink` has `internal` abstract methods which are impossible to override except in Nuke assembly.

```
        internal abstract void WriteNormal(string text);
        internal abstract void WriteSuccess(string text);
        internal abstract void WriteTrace(string text);
        internal abstract void WriteInformation(string text);
```

In order to allow to create custom OutputSinks, those methods should be `protected internal`.

Closes: https://github.com/nuke-build/nuke/issues/699

I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

### CODE REVIEW

**Comment by matkoch** [comment]
What's the issue?

**Comment by cmenzi** [comment]
> What's the issue?

Basically, I like to create an OutputSink for GitLab, which has been removed, with coloring and collapsing. Maybe, once I have a good solution for this, I can provide it to Nuke again.

2nd: When the SDK provides me a public abstract class, I assume that I'm allowed to derive from it. This is currently not possible, because of the `internal abstract` methods, which the compiler enforces to be implemented.

image

So, I think either OutputSink should be completely internal or if public, then it should work.

**Comment by matkoch** [comment]
I'm asking about the functional issue. I know how the internal modifier works. It exists so that people don't just patch issues in their code, but have an interest to contribute it as a fix to the project. OutputSinks don't contain a lot of magic, so I'm sure a fix can also be provided without having these extension points to test.

We never had a `GitLabOutputSink`, so not sure what you mean that it had been removed.

**Comment by cmenzi** [comment]
Yes, you are right, there was never a `GitLabOutputSink` , but it was just a fallback the OutputSink.Default. I think, there was a switch statement at some time, before you introduced the Host abstraction.

Ok. Let's try again. 

Basically, GitLab also uses Ansi coloring for the job logs and allows to collapsible sections.

- https://docs.gitlab.com/ee/ci/yaml/script.html#add-color-codes-to-script-output
- https://docs.gitlab.com/ee/ci/jobs/#expand-and-collapse-job-log-sections

I would really like to provide this feature in via PR. But I'm just not sure how write such a integration test for this. That's why I first liked to implement the GitLabOutputSink on my side, and then provide it Nuke.


<blockquote><div><strong><a href="https://docs.gitlab.com/ee/ci/yaml/script.html#add-color-codes-to-script-output">GitLab CI/CD script syntax | GitLab</a></strong></div><div>Documentation for GitLab Community Edition, GitLab Enterprise Edition, Omnibus GitLab, and GitLab Runner.</div></blockquote>
<blockquote><div><strong><a href="https://docs.gitlab.com/ee/ci/jobs/#expand-and-collapse-job-log-sections">Jobs | GitLab</a></strong></div><div>Documentation for GitLab Community Edition, GitLab Enterprise Edition, Omnibus GitLab, and GitLab Runner.</div></blockquote>

**Comment by matkoch** [comment]
There are no tests for such things. Just prepare all the different output
strings outside from an OutputSink, and then we can integrate it.

**Comment by cmenzi** [comment]
Just added another PR: https://github.com/nuke-build/nuke/pull/708

Maybe we can close this.

**Comment by matkoch** [comment]
Thanks, will have a look.

**Pull request closed without merging**
