### PR TITLE
Adds Terraform tasks

### PR DESCRIPTION
**Pull request by matt-psaltis**
This PR adds Terraform to the CLT system it provides:

* Initialize
* Plan
* Validate
* Apply
* Refresh
* Force-Unlock
* Graph

I confirm that the pull-request:

- [X] Follows the contribution guidelines
- [X] Is based on my own work
- [X] Is in compliance with my employer

### CODE REVIEW

**Comment by matkoch** [comment]
Not clear why there is non-generated code

**Comment by lynkz-matt-psaltis** [comment]
Hi @matkoch could you please help me to understand your feedback so I can action some changes. I had just completed another PR for some updates to the Helm tool. In creating this PR, I followed the same code structure as that particular tool already had defined. Where did I go wrong?

**Comment by matt-psaltis** [comment]
Hi @matkoch could you please help me to understand your feedback so I can action some changes. I had just completed another PR for some updates to the Helm tool. In creating this PR, I followed the same code structure as that particular tool already had defined. Where did I go wrong?

**Comment by matkoch** [comment]
Helm is just different for IDK what reason. You shouldn't need anything custom from what I see.

**Comment by matt-psaltis** [comment]
Ah ok I chose the edge case damn - I'll base it on a different one. Thanks!

**Pull request closed without merging**
