### PR TITLE
Ensured that the SonarQube verbose flag is lower-cased

### LINKED ISSUE #874: Sonar EnableVerbose dosen't work
### Usage Information

6.0.1 / .NET 6

### Description

When enabling sonar verbose get the following warning and sonar doesn't output verbose
`[DBG] WARNING: Expecting the sonar.verbose property to be set to either 'true' or 'false' (case-sensitive) but it was set to 'True'.`

### Reproduction Steps

```
sonarScannerBeginSettings.EnableVerbose()
```

### Expected Behavior

Sonar to output verbose logs

### Actual Behavior

Verbose logs are not shown

### Regression?

_No response_

### Known Workarounds

_No response_

### PR DESCRIPTION
**Pull request by dennisdoomen**
Fixes #874

Also includes a proposal on how to test such a thing. Please let me know what you think of that.

I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

### CODE REVIEW

**Comment by matkoch** [comment]
Isn't this (lower-case boolean) also relevant for all other properties that are boolean?

**Comment by dennisdoomen** [comment]
> Isn't this (lower-case boolean) also relevant for all other properties that are boolean?

Could be. But this one triggered a warning/error in the SQ logs.

**Comment by matkoch** [comment]
Could you check with another parameter perhaps? If it's not working, then I'd like to fix the other parameters as well. If it's working, then it's rather a bug for SonarQube.

**Comment by dennisdoomen** [comment]
I don't have access to a SQ environment for the next couple of weeks (because I switched clients), but it's very likely that it's going to able to other boolean parameters as well.

**Comment by matkoch** [comment]
There's another flag to write less code. Committing manually, but thanks for bringing this up.

**Comment by dennisdoomen** [comment]
> There's another flag to write less code. Committing manually, but thanks for bringing this up.

What do you mean with that?

**Comment by matkoch** [comment]
`customValue` instead of `customImpl`

**Pull request closed without merging**
