### PR TITLE
Add support for Nerdbank GitVersioning

### PR DESCRIPTION
**Pull request by macsux**
I confirm that the pull-request:

- [ X] Follows the contribution guidelines
- [ X] Is based on my own work
- [ X] Is in compliance with my employer

### CODE REVIEW

**Comment by tunger** [comment]
@matkoch is there something left to do? I'd be interested as well in this feature.

**Comment by matkoch** [comment]
@tunger yes I was also looking at it again, because I wanna switch from GitVersion.

One thing we need to figure out is how the task name should be. `NerdbankGitVersioning` looks a bit long, especially when you consider the attribute:

```
[NerdbankGitVersioning] NerdbankGitVersioning GitVersion;
```

I'm actually leaning more towards

```
[Nbgv] Nbgv Nbgv;
```

What do you think?

**Comment by GeorgDangl** [comment]
Actually, I'd just prefer the long name - then at least I don't have to figure out what `Nbgv` means😀

Also unrelated to the PR, @matkoch, why do you want to switch?

**Comment by macsux** [comment]
This PR has been hanging for a long time.. Any reason it's not getting
merged?

**Comment by matkoch** [comment]
@macsux it's being discussed currently, right? As always the reason is "limited time"...

**Comment by tunger** [comment]
@matkoch I also like verbose names better. It's usually only the declaration that gets this long. `nbgv` is fine for the dotnet global tool as you potentially write that more often, but I don't see a reason to shorten it here.

**Comment by matkoch** [comment]
@tunger, maybe `NerdbankGitVersion` at least? dropping the `ing` for both attribute and tasks?

**Comment by tunger** [comment]
@matkoch well, I'd still go for the same name as the repo, but `NerdbankGitVersion` seems like a good compromise ;) 
I looked at what the maintainer called his packages, mostly he uses the full name ([npm](https://www.npmjs.com/package/nerdbank-gitversioning), [github action](https://github.com/marketplace/actions/nerdbank-gitversioning), [nuget](https://nuget.org/packages/Nerdbank.GitVersioning)), as for Cake he uses [GitVersioning](https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/cake.md). But that's ambigious regarding GitVersion.
It's your call :)

**Pull request merged**
