### PR TITLE
Fix PowerShell build script path in build.cmd

### PR DESCRIPTION
**Pull request by atifaziz**
`build.cmd` builds an invalid path to `build.ps1`.

Suppose this repo has been locally cloned to `A:\nuke`. Running `build.cmd` will run PowerShell with the following command line:

    powershell -ExecutionPolicy ByPass -NoProfile "A:\nuke\build.cmd"\..\build.ps1

The are two problems:

1. `%0` expands to the file name of the running batch, not its path.
2. `build.ps1` is in the same directory as `build.cmd` and not in the parent (ie `..`).

This PR fixes both problems (and uses proper quoting) such that PowerShell gets executed as follows:

    powershell -ExecutionPolicy ByPass -NoProfile A:\nuke\build.ps1

---
I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

### CODE REVIEW

**Comment by matkoch** [comment]
Thanks. Could you fix that in the template too?

**Comment by matkoch** [comment]
I'm unsure though about the quoting. What happens if the directory contains spaces? Should it be `"%~dp0build.ps1"` ?

**Comment by atifaziz** [comment]
> What happens if the directory contains spaces? Should it be `"%~dp0build.ps1"` ?

Good catch! I don't know how I missed those when I claimed to address quoting! 🤦🏼‍♂️ Anyway, fixed with de6f9490c0c0ff8ba3e5872e3ec9919e1a669aff.

**Comment by matkoch** [comment]
And in the template please: src/Nuke.GlobalTool/templates

**Comment by atifaziz** [comment]
> And in the template please: src/Nuke.GlobalTool/templates

Just was applying that as you wrote! Just pushed it in 3f66e3b3ad2d88031a102711e7cc7dcd5cf21a6a.

**Comment by matkoch** [comment]
Thanks for your contribution! 😄🎉

**Pull request merged**
