### PR TITLE
Add --no-build to dotnet publish

### PR DESCRIPTION
**Pull request by LordMike**
It seems this option is missing.. :)

### CODE REVIEW

**Comment by matkoch** [comment]
Hi @LordMike, thanks for this. Could you also use the official help text instead? It is:

> Doesn't build the project before publishing. It also implicitly sets the &lt;c&gt;--no-restore&lt;/c&gt; flag.

**Comment by LordMike** [comment]
I've updated the help text, but I'm unsure what bitrise CI is complaining about (I can't see the logs)

**Comment by matkoch** [comment]
Don't worry about Bitrise. Our infrastructure will change pretty soon. Could you just regenerate as described in the other issue?

**Comment by matkoch** [comment]
PS: Sorry, should have said that right away :)

**Comment by matkoch** [comment]
Thanks for your contribution! 😄🎉

**Pull request merged**
