### PR TITLE
Support Jenkins Pipeline Generation

### PR DESCRIPTION
**Pull request by Matze693**
Introduction of a new JenkinsAttribute to generate Jenkinsfiles based on Nuke execution plan.
Jenkins has so many features, possibilities, plugins, etc., but my goal was to map the behavior of Nuke in a Jenkins environment.

I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

### CODE REVIEW

**Comment by matkoch** [comment]
Can xunit reports be reported via service messages perhaps? Defining reporting in attributes violates abstraction..

**Comment by Matze693** [comment]
Specifying the concrete report type is not ideal. But unfortunately I see no other solution at the moment :see_no_evil:

What's your idea with _service messages_?

**Comment by matkoch** [comment]
Many CI systems allow service messages to achieve the same effect (ordinary `Console.WriteLine` basically, which gets discovered by the CI system).

**Comment by Matze693** [comment]
As far as I know, this is not supported by XUnit or generally by the Jenkins system.

**Comment by matkoch** [comment]
Little heads-up: the PR is much appreciated, but I need to postpone it to the next release (5.2.0). Will come back here asap.

**Comment by Matze693** [comment]
Hi @matkoch, what do you think, when will there be a new version with the Jenkins configuration? we are looking forward to it.

**Comment by matkoch** [comment]
It will take a little more unfortunately. The main blocker is the time to get a personal instance of Jenkins running to test it. FYI, 5.2.0 is going to be released with the new telemetry features only, so 5.3.0 will probably be the fix version.

**Comment by matkoch** [comment]
Sorry, this became too outdated. I don't have a Jenkins instance to test, which is my primary problem for merging.

**Comment by Matze693** [comment]
@matkoch okay I see, but we need this feature. Is it then possible to set the classes `Nuke.Common.ValueInjection.ParameterService` and `Nuke.Common.ValueInjection.ValueInjectionUtility` to public, that we can implement the Jenkins pipeline generation stuff on our side?

**Comment by pfeigl** [comment]
We would have really loved to have this feature too. Is there anything we can help with to get this finished?
Like providing a Jenkins environment until this is finalized or provinding help in setting up good environments using docker to run tests against?

**Pull request closed without merging**
