### PR TITLE
Implement trigger branches, tags, and paths config for Azure Pipelines attribute

### PR DESCRIPTION
**Pull request by esond**
I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

---
The Azure Pipelines configuration attribute now generates trigger branches, tags, and paths in the `azure-pipelines.yml` file according to [the schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?#triggers).

This only partially covers the possible triggers, there are PR triggers and scheduled triggers as well, but as this is my first contribution, I figured I would make sure I had the rhythm before I implemented the other trigger types.

### CODE REVIEW

**Comment by esond** [comment]
Well look at me go, I managed to make the macOS build time out.

I don't believe this is related to my work, but I can't re-run the failed job to check. Any ideas?

**Comment by matkoch** [comment]
@esond looks good! Thank you so much. But it will take me a bit of time to actually merge it. I recently started streaming my work on the project. If you wanna join, it will happen faster :)

**Comment by esond** [comment]
@matkoch That sounds cool! Do you mean you're steaming on twitch or something? I've heard of and seen people streaming their development, but I've never spent much time watching. I'd consider "joining in" if I knew a little more about just what that entailed.

**Comment by matkoch** [comment]
You have the choice... you could either just join with chat, or with skype (video optional).

**Comment by esond** [comment]
I will give you a follow and check it out next chance I get!

Eric Sondergard
Hexagram Solutions
ericsondergard@fastmail.com
403-815-7767

**Comment by esond** [comment]
@matkoch Sadly, I think that our respective geographic locations (🇨🇦 🇩🇪) will make it difficult for me to collaborate in any meaningful way. But I will check it out when I get the chance!

**Comment by matkoch** [comment]
I can make any time happen! Just suggest one or two datetimes :)

**Comment by matkoch** [comment]
Thanks for your contribution! 😄🎉

**Pull request merged**
