### PR TITLE
Pulumi tool support

### PR DESCRIPTION
**Pull request by nloum**
Don't merge this yet please.

Will CI produce a build that I can test? Or do I need to build it locally first?

This is for #557 

---

I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer
- [ ] Has been tested

### CODE REVIEW

**Comment by Hawxy** [comment]
I was working on pulumi support 5-8 months ago but completely forgot to finish it off and open a PR, I have the *.json that was completed for everything apart from `create`, if it's of any help. I think I have some duplicate consolidation and an enum not present in your version, however yours is more up to date:

https://gist.github.com/Hawxy/39612f99f0c1c2db0b6417d8e5cdf636

You will also want a custom logger to prevent warnings from being output as errors, I had something like:

```csharp
    //Super naive logger, just designed to suppress common errors.
    internal static void CustomLogger(OutputType type, string text)
    {
        var output = text.TrimStart();

        switch (type)
        {
            case OutputType.Std:
                Logger.Normal(text);
                break;
            case OutputType.Err:
            {
                if (output.StartsWith("warning:")
                    Logger.Warn(text);
                else
                    Logger.Error(text);
                break;
            }
        }
    }
```
>  Or do I need to build it locally first?

AFAIK you should be able to run the `GenerateTools` task locally which will allow you test the output.

**Comment by nloum** [comment]
@Hawxy thanks! I've added a custom logger like that and found the code generation task, so I'll begin testing. It will probably take several days.

**Comment by matkoch** [comment]
@nloum did you generate the json file?

**Comment by nloum** [comment]
I got everything done except for testing and any changes based on the testing results. I've been busy with other things lately but I should get to testing this soon.

**Comment by matkoch** [comment]
Wasn’t my question :) did you generate the metadata itself?

**Comment by nloum** [comment]
Ah right. I did not generate Pulumi.json. I hand-coded everything in there, including the help text. Is that the metadata you're talking about?

Obviously Pulumi.Generated.cs was generated. PulumiTasks.cs I copied from other code in the repo.

**Comment by matkoch** [comment]
https://github.com/pulumi/pulumi/issues/4239

**Comment by nloum** [comment]
@matkoch I just started testing this and things look good, so I'm okay with merging what I'm working with. However it looks like `Pulumi.Generated.cs` didn't end up in the merge for some reason. [This](https://github.com/nloum/nuke/tree/develop/source/Nuke.Common/Tools/Pulumi) is the code I've been testing and [this](https://github.com/nuke-build/nuke/tree/develop/source/Nuke.Common/Tools/Pulumi) is the result of your merge. Shouldn't the `Pulumi.Generated.cs` file be checked in?

**Comment by matkoch** [comment]
That's fine, don't worry. I generate those files before release.

**Pull request merged**
