### PR TITLE
Fixes the nuget publish function for azure repositories

### PR DESCRIPTION
**Pull request by toadicusrex**
I had a lot of difficulty getting my nuget packages to deploy to our Azure Devops feed.  What I found out was that it required some slight changes and a "nugetauthenticate" task that authenticated against the nuget feed.  I built nuke, packaged it, and published to our corporate nuget feed to test it and was successful (finally) in getting it to work.    I'm happy to try stuff if I've done something wrong or I've missed some larger context.  Thank you!

I confirm that the pull-request:

- [X] Follows the contribution guidelines
- [X] Is based on my own work
- [X] Is in compliance with my employer

### CODE REVIEW

**Comment by toadicusrex** [comment]
Oh... so sorry about the whitespace changes!  I just realized those, I use tabs over spaces.  If you'd like me to switch those I'm happy to do so (I'll go read the guidelines, I've probably missed something).

**Comment by matkoch** [comment]
Did you take the time to review your own PR before pushing it here?

**Comment by toadicusrex** [comment]
I did have someone look the changes over, and I've deployed it to my azure nuget feed.  I used that nuget to deploy another project (as a nuget) to the same feed, which works beautifully.  I am working largely alone, but if there's something you'd like me to do to validate I'm happy to do that.  There was a chat with Rasmus Toft Lauridsen some time ago where I went through the process I was following and some of the issues I was having.  Is that what you're referring to?

**Comment by toadicusrex** [comment]
The principle is that for azure devops (cloud) artifact feeds I have to "authenticate" as a step against that feed before I can push up to it.  I figured it shouldn't be mandatory, so I made it as a separate addable step.

**Comment by toadicusrex** [comment]
I'm sorry - I had looked it over before committing but apparently didn't look hard enough.  Let me know if there are any other changes you'd like, happy to keep working on it so that it meets your standards.

**Pull request closed without merging**
