### PR TITLE
Add DocFXTasks custom logger

### PR DESCRIPTION
**Pull request by billhenn**
The changes add a custom logger for DocFX to properly report warning and error messages.

I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

### CODE REVIEW

**Comment by bitbonk** [comment]
I still don't know enough about NUKE, but in regards to  docfx this looks great to me. When using Nuke this will solve https://github.com/dotnet/docfx/issues/6894

**Comment by matkoch** [comment]
@billhenn thanks for the PR, I have concerns though regarding the regex :)

1. It's not clear to me if with a different culture, this regex will actually fail.
2. Given that the regex has a fixed number of digits, it seems easier to just use `Substring` guarded with `str.Length`.

If we use the `Substring` approach, please check how the time is printed. If it's using the `CultureInfo`, we might just check and save the length to proceed as described.

**Comment by billhenn** [comment]
@matkoch I don't know DocFX's codebase at all but their console writing logic seems to be in the Microsoft.DocAsCode.Common.ConsoleLogListener class and is implemented via this line:

```
var now = DateTime.UtcNow.ToString("yy-MM-dd hh:mm:ss.fff");
```

It's your call how you want to handle the regex.  I used it because I could easily detect the various warning/error and that all this occurred at the start of a line.

**Comment by matkoch** [comment]
Regex matching takes much more time than using substring. It's just unnecessary here imo.

**Pull request merged**
