### PR TITLE
Handle Lower Cased `gitversion.dll`

### PR DESCRIPTION
**Pull request by iwillspeak**
Versions of GitVersion.tool newer than 5.2.0 appear to have changed the case of
the executable and dll. This prevents the tool from being found in the newer
releases.

I confirm that the pull-request:

- [x] Follows the contribution guidelines
- [x] Is based on my own work
- [x] Is in compliance with my employer

### CODE REVIEW

**Comment by iwillspeak** [comment]
~This should probably be abandoned in preference for #510 / #509~

Edit: If #510 isn't the right way to solve the `GitVersion.dll` vs `gitversion.dll` issue I guess this PR is back on.

**Comment by BLaZeKiLL** [comment]
any update on this ?

**Comment by iwillspeak** [comment]
If you check out the package feed on my fork there's pre-release builds of this you can use:

https://github.com/iwillspeak/nuke/packages

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/iwillspeak/nuke">iwillspeak/nuke</a></strong></div><div>The AKEless Build System for C#/.NET. Contribute to iwillspeak/nuke development by creating an account on GitHub.</div></blockquote>

**Comment by bqv** [comment]
Any reason not to merge this?

**Comment by bqv** [comment]
@matkoch ?

**Comment by iwillspeak** [comment]
It looks like the fix for case insensitive lookups on .NET Core in #510 has been merged to develop. I guess that with that solution this special casing of GitVersion isn’t needed.

**Pull request closed without merging**
