### PR TITLE
Add linux replacement of $-variables

### LINKED ISSUE #165: Expand variables on Unix
https://github.com/nuke-build/nuke/blob/c209e6ad6057f70d735f0427fd5eccd217f96426/source/Nuke.Common/EnvironmentInfo.Others.cs#L28-L32

### PR DESCRIPTION
**Pull request by LordMike**
Fixes #165 

Uses a regex of `\$([a-z0-9_\-]+)` to locate `$VARIABLES` and replace them using regex's replacer.

### CODE REVIEW

**Comment by LordMike** [comment]
Is it possible to write unit tests for the different platforms?

**Comment by LordMike** [comment]
Tested. Run by hacking the Environment to simulate Linux/Windows.

```csharp
            Console.WriteLine("Win: " + EnvironmentInfo.ExpandVariables("%SystemDrive%"));
            Console.WriteLine("Únx: " + EnvironmentInfo.ExpandVariables("$SystemDrive"));
```

```
As Windows:
Win: C:
Unx: $SystemDrive

As Linux:
Win: C:
Unx: C:
```

**Comment by LordMike** [comment]
So. I ran it on linux in WSL, and found that .NET's `Environment.GetEnvironmentVariable()`  is case-sensitive.  If this is the intended behaviour, then all is ok. Else the code needs to have its Environment lookup thingy tweaked.

**Comment by LordMike** [comment]
Fixed regex to `\$([a-z_][a-z0-9_]*)`, given this [SO answer](https://stackoverflow.com/a/2821183).

**Comment by matkoch** [comment]
I force-pushed a draft how I would like the method to look like. One thing that's missing, is expansion for `~` to the home directory. Only at the beginning of the string.

**Comment by LordMike** [comment]
I've added the expansion

**Comment by LordMike** [comment]
Why not use `ReplaceRegex` for both replacements?

**Comment by matkoch** [comment]
How exactly? Feel free to commit.

**Comment by LordMike** [comment]
One could even interleave the two replacements (doing a regex like `(^~| ... )` and then doing an if in the evaluator) :P

**Comment by matkoch** [comment]
Looks better, thanks! But why ignore case? I think that should be removed. I will do it myself when merging, if you agree.

**Comment by LordMike** [comment]
Well. That, or change the regex to `\$([a-zA-Z_][a-zA-Z0-9_]*)`.

**Comment by matkoch** [comment]
Ah sorry, I confused it with replacing the variable matching case-insensitive. I guess it's correct like it is.

**Comment by matkoch** [comment]
Thanks for your contribution :)

**Pull request merged**
